unit uFmxStrConsts;

interface
const
  cUser_IimageStyleNameMask = 'user_image_%d_style';
  cMin='Минимум';
  cMax='Максимум';
  cModulePriority='Приоритет';
  cSynchroChannel='Канал синхронизации';
  cAntiShatterFilter='Фильтр антидребезга';
  cAntiShatterFilterTime='Время фильтра антидребезга';
  cUnitPriority='Предпочтение';
  cFull='Полный размер';
  cImpulseOutput='Импульсное управление';
  //Shape
  сShapeName='Фигура ';
  cBColor='Цвет фона';
  cBStartColor='Цвет начала';
  cBEndColor='Цвет окончания';
  cBOpacity='Прозрачность фона';
  cBStyle='Стиль фона';
  cPColor='Цвет рамки';
  cPOpacity='Прозрачность рамки';
  cPStyle='Стиль рамки';
  cPWidth='Толщина рамки';
  cShapeBaseKind='Основная фигура';
  cShapeExtraKind='Вспомогательная фигура';
  cShapeOpacity='Прозрачность фигуры';
  cShapeDirection='Направление';
  cShapeColorGray='Серый';
  cShapeColorBlue='Синий';
  cShapeColorGreen='Зеленый';
  cShapeColorRed='Красный';
  cShapeColorYellow='Желтый';
  cShapeColorNotAssigned='Не определен';


  cKInput='К вход';
  cKOutput='К выход';
  cInterval='Интервал';
  cNumber='Число';
  cMask='Маска';
  cParityD='Четность (D)';
  cParityU='Четность (U)';
  cParity='Четность';
  cScale='Масштаб';

  cConfig_I='Каналы измерения тока ';
  cConfig_U='Каналы измерения напряжения ';
  cConfig_F='Каналы счета импульсов ';

  cAmpermeterName='Канал измерения тока ';
  cVoltmeterName='Канал измерения напряжения ';
  cCounterName='Канал измерения частоты ';

  cWeightExt=' кг';
  cDeviceType='Тип датчика';
  cSerialNum='Серийный номер';
  cTypeOfProtocol='Тип протокола';
  cTypeOfProtocolD='Тип протокола(D)';
  cTypeOfProtocolU='Тип протокола(U)';
  cTypeOfProtocolI='Тип протокола(I)';
  cTypeOfProtocolF='Тип протокола(F)';
  cTypeOfInput='Тип входа(F)';
  cImpulseWeight='Цена импульса';
  cManualEnter='Ручной ввод: ';
  cModbusInputReg='Регистр ввода';
  cModbusOutputReg='Регистр вывода';
  cModbusInputRegD='Регистр ввода(D)';
  cModbusInputRegU='Регистр ввода(U)';
  cModbusInputRegI='Регистр ввода(I)';
  cModbusInputRegF='Регистр ввода(F)';
  cModbusOutputRegD='Регистр вывода(D)';
  cModbusOutputRegU='Регистр вывода(U)';
  cModbusFormat='Формат данных';

  cEdIzmSensor='Ед.изм. датчика';
  cMassMode='Измерение массы';
  cEdIzmParam='Ед.изм. параметра';
  сIVTMName='ИВТМ ';
  сDiscretValveName='Дискретная задвижка ';
  cBlcedValveName='Механизм слива ';
  cFCDName='Устройство переключения потока ';
  cFlowmetersPanelName='Панель подключения ';
  сEditName='Поле ввода ';
  сTEXTName='Текст ';
  сPIPEName='Труба ';
  сGAUGEName='Уровень жидкости ';
  сShemeName='Элемент ';
  сSWITCHName='Отключатель ';
  cHeaterName='Контактор нагревателя ';
  cLevelDetectorName='Датчики уровня ';
  cSSDetectorName='Датчики слива ';
  сUnoperatedFlowValveName='Вспомогательная задвижка нерегулируемого насоса ';
  cFlowPumpName='Управляемый насос потока ';
  cScaleName='Весовое устройство ';
  сThermometerName='Термометр ';
  сBarometerName='Барометр ';
  сHygrometerName='Гигрометр ';
  сManometerName='Манометр ';
  сTermogigrometerName='Термогигрометр ';
  сPressurePumpName='Повысительный насос ';
  сUnoperatedFlowPumpName='Нерегулируемый насос потока ';
  сElectricValveName='Регулируемая задвижка ';
  cFlowmeterName='Эталонный расходомер ';
  cFlowmeterMin='Минимальный расход, м3/ч';
  cFlowmeterMax='Максимальный расход, м3/ч';
  cFlowmeterMassCounter='Массовый';
  cUsingMode='Режим работы';
  cTypeAppFunc='Тип функ. номера';
  cFromBalance='Из весов';
  cReadOnly='Только чтение';
  cChannelsCount='Каналов';
  cWeight='Масса';
  cDChannelsCount='D входов';
  cFChannelsCount='F входов';
  cFModulesCount='F модулей';
  cIChannelsCount='I входов';
  cUChannelsCount='U входов';
  boolnames:array[boolean]of string=('Нет','Да');
//  _boolnames:array of TArray<string>=['Нет','Да'];
  malenames:array[boolean]of string=('закрыт','открыт');
  movingnames:array[boolean]of string=('закрытие','открытие');
  femalenames:array[boolean]of string=('закрыта','открыта');
  pumpstatenames:array[boolean]of string=('выключен','работает');
  fcdstatenames:array[boolean]of string=('Пролетная труба','Весовой бак');
  cCoilNames='Наименования битов';
  cCoilCheckListName='Битовый список';
  cHeader='Заголовок';
  сFrameName='Рамка';
  сText='Текст';
  сGauge='Уровень жидкости';
  сName='Наименование';
  cHint='Подсказка';
  cFont='Шрифт';
  cFontSize='Размер текста';
  cFontColor='Цвет текста';
  cFrameColor='Цвет рамки';
  cFrameSize='Толщина рамки';
  cFrameDash='Тип рамки';
  cFrameStrokeSolid='Solid';
  cFrameStrokeDash='Dash';
  cFrameStrokeDot='Dot';
  cFrameStrokeDashDot='DashDot';
  cFrameStrokeDashDotDot='DashDotDot';
  cValue='Значение';

  cSize='Размер';
  cStyle='Стиль';
  cColor='Цвет';
  cOpacity='Прозрачность';
  cStretch='Растягивание';
  cOrientation='Горизонтальная ориентация';
  cOutlay='Расход';
  cPipe='Труба';
  cPipe2='Труба 2';
  cPipe3='Труба 3';
  cDevice='Устройство';
  cPump='Рег. насос';
  cUnoperatedPump='Дискр. насос';
  cPnevmo='Зап. клапан';
  cBlcedValve='Слив. клапан';
  cElectro='Задвижка';
  cUPP='УПП';
  cFlowInverse='Реверс';
  cStateInverse='Инверсия';
  cActive='Активность';
  cEdIzm='Ед.измерения';
  cMiniIntegrator='Усреднение';
  cTankPosition='Положение бака';
  cTankToLeft='Слева';
  cTankToRight='Справа';

  cPort='Порт';
  cAddress='Адрес';
  cBaudrate='Скорость';
  cModuleType='Тип модуля';
  cNumContact='№ контакта';
  cNumChannel='№ канала';
  cNumCounters='Счетчиков';
  cInputContact='Вход';
  cActiveColor='Активный цвет';
  cPassiveColor='Пассивный цвет';
  cNumContactInp='№ вх.конт.';
  cNumContactOut='№ вых.конт.';
  cNumContactInp2='№ вх.конт. откл.';
  cNumContactOut2='№ вых.конт.откл.';


  cPortI='Порт(I)';
  cAddressI='Адрес(I)';
  cBaudrateI='Скорость(I)';
  cModuleTypeI='Тип модуля(I)';
  cModuleChannelI='Каналов в модуле(I)';
  cNumContactI='№ канала(I)';
  cMaxInput='Максимум(I)';
  cMinInput='Минимум(I)';
  cMaxInputU='Максимум(U)';
  cMinInputU='Минимум(U)';
  cMaxOutput='Максимум(O)';
  cMinOutput='Минимум(O)';
  cMinFreq='Мин. частота, Гц';
  cMaxFreq='Макс. частота, Гц';
  cMaxOutlay='Максимальный расход';

  cPortD='Порт(D)';
  cAddressD='Адрес(D)';
  cBaudrateD='Скорость(D)';
  cModuleTypeD='Тип модуля(D)';
  cNumContactD='№ канала(D)';

  cPortU='Порт(U)';
  cAddressU='Адрес(U)';
  cBaudrateU='Скорость(U)';
  cModuleTypeU='Тип модуля(U)';
  cModuleChannelU='Каналов в модуле(U)';
  cNumContactU='№ канала(U)';

  cPortF='Порт(F)';
  cAddressF='Адрес(F)';
  cBaudrateF='Скорость(F)';
  cModuleTypeF='Тип модуля(F)';
  cModuleChannelF='Каналов в модуле(F)';
  cNumContactF='№ канала(F)';
  cDigitsForChannel='Цифр на канал';

  cLeft='Cлева';
  cTop='Cверху';
  cWidth='Ширина';
  cHeight='Высота';
  cSynchro='Синхронизация';
  cTypeAppFunction='Тип функции';
  cNumAppFunction='Функц.номер ';
  c_OpenContact='№ кон."ОТКР"';//для линий управления
  c_CloseContact='№ кон."ЗАКР"';
  cOpenContact='№ выхода "ОТКР"';//для линий управления
  cCloseContact='№ выхода "ЗАКР"';
  cOpenSensor='№ входа "ОТКР"';//для линий контроля концевых выключателей
  cCloseSensor='№ входа "ЗАКР"';
  cSwitchTime='Время переключения';
  сFeedback='Обратная связь';
  cTwoControls='Два управляющих выхода';
  cFemale='Женский род';
  cInitState='Начальное состояние';
  cVisible='Видимость';
  cZPosition='Z-позиция';
  cView='Вид';
  cAngle='Угол';
  cRowHeight='Высота строки';
  cState='Состояние';
  cButtonVisible='Видимость кнопки';
  cUse_L2='Коррекция';
  cFirst='Первый';
  cAFTypeSet='Набор функций';
  cSensorsQuantity='Датчиков';
  cDigits='Точность';
  cUSE_T='Датчик T';
  cUSE_H='Датчик H';
  cUSE_P='Датчик P';
  cShadow='Тень';
  cYes='Да';
  cNo='Нет';
  cStop='Останов';
  cOpenCaption='открыт';
  cCloseCaption='закрыт';
  cStandart='Классика';
  cOtherView='Расширенный';
  cInverse='Инверсия';

  //Заголовки
  cFreqHeader='Частота, Гц';
  cOulayVolumeHeader='Расход, м3/ч';
  cOulayMassHeader='Расход, т/ч';
  cImpHeader='Импульсов, шт';
  cVolumeHeader='Объем, л';
  cMassHeader='Масса, кг';
  cTimeHeader='Время, сек';

//Фигуры
  cElbow='Колено';
  cPipe_H='Труба-Г';
  cPipe_V='Труба-В';
  cTee='Тройник';
  cCross='Крестовина';
  cScaleTank='Весовой бак';
  cMainTank='Емкость';
  cTank_H='Рессивер-Г';
  cTank_V='Рессивер-В';
  cFlange='Фланец';
  cValve='Клапан-А';
  cValve_C='Клапан-З';
  cValve_O='Клапан-О';
  cPump_1='Насос-1';
  cPump_2='Насос-2';
  cPump_3='Насос-3';
  cPump_4='Насос-4';
  cText='Текст';
  cGroupBox='Рамка';
  cUser_1='Прмитив-1';
  cUser_2='Прмитив-2';
  cUser_3='Прмитив-3';
  cUser_4='Прмитив-4';
  cUser_5='Прмитив-5';
  cUser_6='Прмитив-6';
  cUser_7='Прмитив-7';
  cUser_8='Прмитив-8';
  cUser_9='Прмитив-9';
  cUser_10='Прмитив-10';
  cUser_11='Прмитив-11';
  cUser_12='Прмитив-12';
  cUser_13='Прмитив-13';
  cUser_14='Прмитив-14';
  cUser_15='Прмитив-15';
  cUser_16='Прмитив-16';
  cUser_17='Прмитив-17';
  cUser_18='Прмитив-18';
  cUser_19='Прмитив-19';
  cUser_20='Прмитив-20';
  cUser_21='Прмитив-21';
  cUser_22='Прмитив-22';
  cUser_23='Прмитив-23';
  cUser_24='Прмитив-24';
  cUser_25='Прмитив-25';
  cUser_26='Прмитив-26';
  cUser_27='Прмитив-27';
  cUser_28='Прмитив-28';
  cUser_29='Прмитив-29';
  cUser_30='Прмитив-30';

//Уровень воды
  cWeightTank='весовой бак';
  cDrainTank='сливной резервуар';



implementation

end.
